name: binary tarball

on: 
    workflow_dispatch:
      inputs:
        debug_enabled:
          type: boolean
          description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
          required: false
          default: false
    release:
        branches: [ master ]
    repository_dispatch:
        types: [linux-binary-test, install-test]
    schedule: 
        - cron: '15  15  *   *   *' # 3:15pm every day
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
        - uses: actions/checkout@v6
        - name: Setup tmate session
          uses: mxschmitt/action-tmate@v3
          if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
          with:
            detached: true
        - name: Setup dependencies
          uses: ./.github/actions/setup-cpp
        - name: download
          run: bash -x .github/workflows/get_binary_release.sh
        - name: Software and db version
          run: ./amrfinder --database_version
        - name: Run tests
          run: |
            bash -x ./test_amrfinder.sh
            cd stx; ./test_stxtyper.sh
