name: binary tarball

on: 
    workflow_dispatch:
    release:
        branches: [ master ]
    repository_dispatch:
        types: [linux-binary-test, install-test]
    schedule: 
        - cron: '15  15  *   *   *' # 3:15pm every day
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: prerequisites
          run: |
              sudo apt-get update
              sudo apt-get install -y hmmer ncbi-blast+ curl build-essential
        - name: download
          run: bash -x .github/workflows/get_binary_release.sh
        - name: software version
          run: ./amrfinder --version
        - name: Run tests
          run: |
              # temporarily we need to download the test script. Can remove
              # once we have a new software release and it's included in the
              # distribution
              curl -L -O https://https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/master/test_amrfinder.sh
              bash test_amrfinder.sh
