name: binary tarball

on: [release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - name: setup
          run: sudo apt-get install -y hmmer ncbi-blast+ curl build-essential
        - name: download
          run: bash -x .github/workflows/get_binary_release.sh
        - name: where are we
          run: |
              pwd
              ls -al
        - name: test protein
          run: |
              ./amrfinder --plus -p test_prot.fa -g test_prot.gff -O Escherichia > test_prot.got
              diff test_prot.expected test_prot.got
        - name: test dna
          run: |
              ./amrfinder --plus -n test_dna.fa -O Escherichia --mutation_all test_dna_mut_all.got > test_dna.got
              diff test_dna.expected test_dna.got
        - name: test combined
          run: |
              ./amrfinder --plus -n test_dna.fa -p test_prot.fa -g test_prot.gff -O Escherichia > test_both.got
              diff test_both.expected test_both.got
