name: C++ CI

on: 
    push:
    repository_dispatch:
        types: [linux-compile-test, install-test]
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: prep
      run: sudo apt-get install -y hmmer ncbi-blast+ git libcurl4-openssl-dev build-essential curl
    - name: make
      run: make
    - name: version
      run: |
          cat version.txt
          ./amrfinder --version
    - name: download db
      run: ./amrfinder -u
    - name: make test
      run: make test
    - name: make gitnub_binaries
      run: make github_binaries
    - uses: actions/upload-artifact@v2
      with:
          name: release-binary
          path: amrfinder_binaries_v*.tar.gz

