name: bioconda CI

on:
    push:
    schedule:
        - cron: '15 4 * * *' # 4:15am everyday

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: prep
      run: sudo apt-get git build-essential curl
    - name: download conda
      run: curl -O https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    - name: install conda
      run: |
          bash ./Miniconda3-latest-Linux-x86_64.sh -b
          export PATH=$HOME/miniconda3/bin:$PATH # Change to match installation location, if not default.
    - name: configure conda channels
      run: |
          conda config --add channels defaults
          conda config --add channels bioconda
          conda config --add channels conda-forge
    - name: install AMRFinderPlus
      run: conda install -y -c bioconda ncbi-amrfinderplus
    - name: activate bioconda
      run: source ~/miniconda3/bin/activate
    - name: test protein
      run: |
          amrfinder --plus -p test_prot.fa -g test_prot.gff -O Escherichia > test_prot.got
          diff test_prot.expected test_prot.got
    - name: test dna
      run: |
          amrfinder --plus -n test_dna.fa -O Escherichia --mutation_all test_dna_mut_all.got > test_dna.got
          diff test_dna.expected test_dna.got
    - name: test combined
      run: |
          amrfinder --plus -n test_dna.fa -p test_prot.fa -g test_prot.gff -O Escherichia > test_both.got
          diff test_both.expected test_both.got
