name: dockerhub test

on: 
    push:
    workflow_dispatch:
    repository_dispatch:
        types: [docker-test, install-test]
jobs:
  get_tests:
    runs-on: ubuntu-latest
    steps:
      - run: | 
          echo "This job should download ncbi/amr from dockerhub and run a simple test"
          echo "downloaded tests, but they won't run in a container"
        name: Run on vm
  container:
    runs-on: ubuntu-latest
    contianer: ncbi/amr:latest
    steps:
      - run: |
          amrfinder --version
          amrfinder --help
          ls -al
        name: Run in container
