name: dockerhub test

on: 
    push:
    workflow_dispatch:
    repository_dispatch:
        types: [docker-test, install-test]
jobs:
  container:
    runs-on: ubuntu-latest
    container: ncbi/amr:latest
    steps:
      - run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
          amrfinder --version
          apt-get install curl
          GIT_BRANCH=master
          curl --silent \
             -O https://raw.githubusercontent.com/ncbi/amr/$GIT_BRANCH/test_dna.fa \
             -O https://raw.githubusercontent.com/ncbi/amr/$GIT_BRANCH/test_prot.fa \
             -O https://raw.githubusercontent.com/ncbi/amr/$GIT_BRANCH/test_prot.gff \
             -O https://raw.githubusercontent.com/ncbi/amr/$GIT_BRANCH/test_both.expected \
             -O https://raw.githubusercontent.com/ncbi/amr/$GIT_BRANCH/test_dna.expected \
             -O https://raw.githubusercontent.com/ncbi/amr/$GIT_BRANCH/test_prot.expected
          amrfinder -p test_prot.fa
        name: Run in container

