name: dockerhub image

on:
    schedule: 
        - cron: '15 21 * * *' # 9:15pm everyday
    workflow_dispatch:
    repository_dispatch:
        types: [docker-test, install-test]

jobs:

  test_dockerhub:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test docker
      run: docker run hello-world
    - name: Version
      run: docker run ncbi/amr amrfinder --version
    - name: Protein
      run: docker run --rm -v ${PWD}:/data ncbi/amr amrfinder --plus -n test_dna.fa -O Escherichia --mutation_all test_dna_mut_all.got > test_dna.got
    - name: Check results
      run: diff test_dna.expected test_dna.got
    - name: Combined
      run: docker run --rm -v ${PWD}:/data ncbi/amr amrfinder --plus -n test_dna.fa -p test_prot.fa -g test_prot.gff -O Escherichia > test_both.got
    - name: Check combined results
      run: diff test_both.expected test_both.got
