name: Docker test 2

on:
    workflow_dispatch:
    push:
        branches: [ master ]
    repository_dispatch:
        types: [docker-test, install-test]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test docker
      run: docker run hello-world
    - name: Version
      run: docker run ncbi/amr amrfinder --version
    - name: Protein
      run: docker run --rm -v ${PWD}:/data ncbi/amr amrfinder --plus -n test_dna.fa -O Escherichia --mutation_all test_dna_mut_all.got > test_dna.got
    - name: Check results
      run: diff test_dna.expected test_dna.got

