name: dockerhub test

on: 
    push:
    workflow_dispatch:
    repository_dispatch:
        types: [docker-test, install-test]
jobs:
  test_dockerhub:
    runs-on: ubuntu-latest
    container: ncbi/amr:latest
    steps:
      - run: |
          echo This job does specify a container.
          echo It runs in the container instead of the VM.
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "GITHUB_REPOSTIORY=${GITHUB_REPOSITORY}"
          echo "GITHUB_REF=$GITHUB_REF"
          amrfinder --version
          apt-get install curl
          GIT_BRANCH=master
          curl --silent \
             -O https://raw.githubusercontent.com/evolarjun/amr/$GIT_BRANCH/test_dna.fa \
             -O https://raw.githubusercontent.com/evolarjun/amr/$GIT_BRANCH/test_prot.fa \
             -O https://raw.githubusercontent.com/evolarjun/amr/$GIT_BRANCH/test_prot.gff \
             -O https://raw.githubusercontent.com/evolarjun/amr/$GIT_BRANCH/test_both.expected \
             -O https://raw.githubusercontent.com/evolarjun/amr/$GIT_BRANCH/test_dna.expected \
             -O https://raw.githubusercontent.com/evolarjun/amr/$GIT_BRANCH/test_dna_mut_all.expected \
             -O https://raw.githubusercontent.com/evolarjun/amr/$GIT_BRANCH/test_prot.expected \
             -O https://raw.githubusercontent.com/evolarjun/amr/$GIT_BRANCH/test_amrfinder.sh
          chmod u+x test_amrfinder.sh
          ./test_amrfinder.sh path
        name: Run tests
        env: 
          GIT_BRANCH: master
          GITHUB_REF: ${{env.GITHUB_REF}}


