name: Mac bioconda
on:
    push:
    workflow_dispatch:
    schedule:
        - cron: '30 3 * * *' # 3:30am everyday
    repository_dispatch:
        types: [mac-bioconda-test, install-test]
jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: configure conda
      run: |
          . $CONDA/bin/activate
          conda config --add channels defaults
          conda config --add channels bioconda
          conda config --add channels conda-forge
          # permissions are messed up on the mac runner
          sudo chown -R 501:20 $CONDA/pkgs
          conda update conda
    - name: install AMRFinderPlus
      run: |
          source /Users/runner/miniconda3/bin/activate
          conda install -y ncbi-amrfinderplus
    - name: version
      run: |
          source /Users/runner/miniconda3/bin/activate
          amrfinder --version
    - name: Download AMRFinderPlus database
      run: |
          source /Users/runner/miniconda3/bin/activate
          /Users/runner/miniconda3/bin/amrfinder -u
    - name: test protein
      run: |
          source /Users/runner/miniconda3/bin/activate
          amrfinder --plus -p test_prot.fa -g test_prot.gff -O Escherichia > test_prot.got
          diff test_prot.expected test_prot.got
    - name: test dna
      run: |
          source /Users/runner/miniconda3/bin/activate
          amrfinder --plus -n test_dna.fa -O Escherichia --mutation_all test_dna_mut_all.got > test_dna.got
          diff test_dna.expected test_dna.got
    - name: test combined
      run: |
          source /Users/runner/miniconda3/bin/activate
          amrfinder --plus -n test_dna.fa -p test_prot.fa -g test_prot.gff -O Escherichia > test_both.got
          diff test_both.expected test_both.got
