name: Mac bioconda
on:
    workflow_dispatch:
      inputs:
        debug_enabled:
          type: boolean
          description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
          required: false
          default: false
    schedule:
        - cron: '15 9 * * *' # 9:15am everyday
    repository_dispatch:
        types: [mac-bioconda-test, install-test]
jobs:
  conda_macos_aarch64:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      with:
        detached: true
    - uses: actions/checkout@v4
    - name: Setup Conda and AMRFinderPlus
      uses: ./.github/actions/setup-conda
    - name: Download AMRFinderPlus database
      shell: bash -el {0}
      run: |
          amrfinder -u
    - name: Software and DB version
      shell: bash -el {0}
      run: |
          amrfinder --database_version
    - name: Download tests
      run: |
          BASE_URL=https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/master
          curl --silent -L -O ${BASE_URL}/test_amrfinder.sh
    - name: Run tests
      shell: bash -el {0}
      run: |
          echo CONDA_PREFIX = $CONDA_PREFIX
          bash ./test_amrfinder.sh -p 
  conda_macos_x86_64:
    runs-on: macos-15-intel
    timeout-minutes: 30
    steps:
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      with:
        detached: true
    - uses: actions/checkout@v4
    - name: Setup Conda and AMRFinderPlus
      uses: ./.github/actions/setup-conda
    - name: Download AMRFinderPlus database
      shell: bash -el {0}
      run: |
          amrfinder -u
    - name: Software and DB version
      shell: bash -el {0}
      run: |
          amrfinder --database_version
    - name: Download tests
      run: |
          BASE_URL=https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/master
          curl --silent -L -O ${BASE_URL}/test_amrfinder.sh
    - name: Run tests
      shell: bash -el {0}
      run: |
          echo CONDA_PREFIX = $CONDA_PREFIX
          bash ./test_amrfinder.sh -p
